### ISSUE TITLE
Split `maintainers` into `current-maintainers` & `previous-maintainers`

### ISSUE THREAD

**Issue by sgoudham** [catppuccin-rfc/userstyles#38]
## Description

It's apparent that the "Thanks To" section doesn't accurately represent the "maintainer" status of the userstyle itself. We should update this to mention current and previous maintainers.

I also think it would be nice if you could look at the YAML and actually see if any ports are unmaintained. I think we should allow `current-maintainers` to be empty so that we're not shying away from the reality of open-source software going unmaintained. Interested to hear @isabelroses' (and anyone else!) thoughts on that.

## Acceptance Criteria

- [ ] `userstyles.yml` is updated to include previous/current maintainers
	- [ ] `userstyles.schema.json` is updated accordingly
- [ ] `README.md` only includes previous/current maintainers and the thanks to section is removed.

E.g.

`userstyles.yml`
```diff
- maintainers: [ *isabelroses, *nekowinston ]
+ current-maintainers: [ *isabelroses ]
+ previous-maintainers: [ *nekowinston ]
```

`README.md`
```diff
- # Thanks To
- 	- Isabel
-   - Winston
+ # Current Maintainer(s)
+  - Isabel
+ # Previous Maintainer(s)
+  - Winston
```

**Comment by isabelroses** [comment]
I do think this is the best course of action.

However, this does mean that we would lose the "thanks to" section that we previously had, like in [catppuccin/discord](https://github.com/catppuccin/discord), which contains a large amount of names. My suggestion is a general thanks file. I'm unsure how this would be managed, but this could be a good addition, because of course each contribution means a lot.

**Comment by nullishamy** [comment]
I feel like "Previous Maintainers" has a negative outlook on what people have done. I would suggest something like "Other contributors". This means that we can group "people who have submitted small changes" and "people not currently maintaining the port" in the same way, which provides clarity on the purpose of the category. 

As it stands, it would be possible to conflate the "small changes" group of people with "people who have maintained it in the past", which goes against the goal(s) laid out here.

In general though, I think this recategorization of maintenance status is a great idea! One thing I might add is people linking their discord (if applicable) in the maintainer area, so that it is easier to initiate off platform discussion. This does not need to exist in the YAML, only in the README.

**Comment by sgoudham** [comment]
I personally don't see a problem with "Previous Maintainers" but interesting perspective, thanks for that. 

I suppose I wanted some separation between "general contributors" and people in the past that have actively maintained the port as it feels odd to group them under one category. I wonder if the following is nicer? @isabelroses @nullishamy 

`userstyles.yml`
```diff
- maintainers: [ *isabelroses, *nekowinston ]
+ current-maintainers: [ *isabelroses ] (speaks for itself)
+ past-maintainers: [ *nekowinston ] (giving some special recognition to a maintainer in the past)
+ other-contributors: [ *nullishamy ] (the maintainer would decide who goes in here? meant to represent general contributions?)
```

The goal of the YAML is to standardise the information and fully auto-generate the READMEs, so if people wanted to add extra information (e.g. discord tags) - it would need to be included in the YAML. I'm unsure if that's beneficial because I'd rather the first port of call is an issue for maximum visibility here and if the maintainer wishes to do so, they could tell them a way to initiate off-platform discussion.

**Comment by nullishamy** [comment]
The new layout seems fine to me. I was mostly concerned about lumping a large group of people together. As for the Discord stuff, it's gonna be easier to just omit, as you described. I had forgotten about the generated README goals. As for the question in the codeblock, I think it would be fine to just have people self include themselves in the other-contributors section, as we did(?) with the "Thanks" section previously.

**Comment by isabelroses** [comment]
To surmise my opinion of this is that it is creating a certain amount of extra work, to an extent I understand the benefits of having the previous maintainers section as it allows anyone to keep track of who they should no longer contact weather they previously thought that way or not. But I see no point in over extending the `General Thanks` section this seems to add unnecessary complexity to something that doesn't need to be there or be auto generated. A better alternative to this would be a simple markdown or text file where people who have contributed generally to the project could mark down their name, but beyond this there is not much benefit to having a autogen script for this. However, I totally support the idea for the maintainers list since this would simplify the locations a single person would have to edit to correct, step down or take on a maintainership of a given userstyle.

**Comment by sgoudham** [comment]
After having implemented it, I'm inclined to agree with you that we don't really need a `other-contributors` section as the commit/PR history should speak for itself.

I'll remove the `other-contributors` field in #43 @isabelroses
